### ISSUE TITLE
ami_occurrences - need better description

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [OpenIntroStat/openintro#13]
Are observations people, days, something else? Docs will need to be updated accordingly.

**Comment by andrewpbray** [comment]
I'm guessing that each obs is a day (there are 365 of them) and the ami is the number of cases in some particular geographic area. I'm pretty sure it comes from this paper:

https://academic.oup.com/aje/article/176/7/642/123210

The figures show the data aggregated at the monthly level, which align roughly with the total counts per month in our data. This is just speculation though =)

**Comment by DavidDiez** [comment]
It is representing the number of occurrences over each day for a year. The data are simulated but representative of real-life data (I couldn't share the actual AMI data I've previously had access to).
