### ISSUE TITLE
Adjust treeDiag() function to have an option to output counts

### ISSUE THREAD

**Issue by DavidDiez** [OpenIntroStat/openintro#17]
For example, rather than give probabilities, show how 1000 cases would cascade through the tree.

**Comment by mine-cetinkaya-rundel** [comment]
Is this still of interest or should I close? I haven't come across a use for it.

**Comment by DavidDiez** [comment]
I think there is a use case for explanatory purposes, which I've used this strategy for. That said, I'm closing this, as it's not being actively worked on, and I don't know when I might do so.
