### ISSUE TITLE
add R Markdown lab report template

### ISSUE THREAD

**Issue by beanumber** [OpenIntroStat/openintro#2]
R Markdown has the ability to create [templates](http://rmarkdown.rstudio.com/developer_document_templates.html). Could we create a lab report template for the _On Your Own_ questions that instructors could use in their classes?

**Comment by andrewpbray** [comment]
This would be great. It looks like the templates are all defined as R functions: https://github.com/rstudio/rticles the format of which...isn't immediately obvious to me.

**Comment by beanumber** [comment]
More relevant info:

http://rmarkdown.rstudio.com/developer_custom_formats.html

**Comment by mine-cetinkaya-rundel** [comment]
Would there be one template for all labs? Or different templates for each lab? The former is cleaner, but the latter is pedagogically better, with earlier templates being more handholdy... Thoughts?

**Comment by beanumber** [comment]
It's a good question -- I was thinking about this as well. I'd say the latter, but does that clutter up the template window too much? With the former, where do the questions go?

**Comment by mine-cetinkaya-rundel** [comment]
My thoughts exactly. Basically I think providing a generic template would just be cosmetic, and might not be all that useful. I do think individual templates might clutter up the template window, but they might still be useful for instructors -- often people ask about the right amount of scaffolding for these labs. But if there is a streamlined happy midpoint I'd be ok with that too (I don't have a good idea).

**Comment by mine-cetinkaya-rundel** [comment]
This is going in the oilabs package so closing the issue here.
