### ISSUE TITLE
rosling_responses mentioned in text but not present in package

### ISSUE THREAD

**Issue by homerhanumat** [OpenIntroStat/openintro#24]
On page 191 the Fourth Edition of the textbook mentions the `rosling_responses` data set:

>"We will use the `rosling_responses` data set to evaluate the hypothesis test ..."

Use of the texttt font for "rosling_responses" suggests that such a data set exists in the package, but it doesn't.

**Comment by mine-cetinkaya-rundel** [comment]
@DavidDiez Do you have this dataset referenced in https://github.com/OpenIntroStat/openintro-statistics/blob/9f527e3498b3ff2e0e0cac2fc9e30208ee683a60/ch_foundations_for_inf/TeX/ch_foundations_for_inf.tex#L1723?

**Comment by DavidDiez** [comment]
Thanks for the note! Sorry for the delay here -- I've now created it and added it to the `openintro` package here on Github.
