### ISSUE TITLE
qqnormsim() ideas

### ISSUE THREAD

**Issue by rpruim** [OpenIntroStat/openintro#26]
1) Use `scales == "free"` or better, add a `scales` argument that defaults to "free".  [Else a sample with an outlier will cause the other plots to look quite different from how they would look if they were generated in isolation.]

2) Don't hard code the number of simulations.  Let 8 be the default if you like.

3) rename first argument?  It's a bit of an odd name.  But I'm guessing it will typically be used without naming, so this is not such a big deal.

4) Consider a version that doesn't label the original data but makes it one of the sample (randomly selecting which location).  Not sure the best way to do the "reveal".

5) Perhaps add a `seed` argument that sets the seed used.  That would solve the reveal issue in one way, since the plot could be generated again withe the original data set distinguished.

6) Complete the documentation and include examples.

**Comment by rpruim** [comment]
Here is an example of the sort of thing I had in mind (some polishing still required).

The use of ggformula isn't necessary and could be avoided.  Even if this doesn't end up in this package, it seems like something along these lines could end up somewhere.  If it ends up in one of the mosaic suite of packages, I expect the first argument would take a formula (`~x`) instead of a bare name.

Currently "hide then reveal" isn't really solved.  Might need to have three options (data is first and identified, data is in a random place and identified, data is in a random place and not identified).  The last two could be used for the "hide then reveal".

``` r
library(ggformula)
library(mosaicData)
library(dplyr)
theme_set(theme_bw())
qqnormsim2 <- function (sample, data, reps = 8, hide = FALSE, ..., scales = "free") 
{
    orig.data <- eval(substitute(sample), data)
    PlotData <-
      expand.grid(rep = 1:(reps + 1), row = 1:nrow(data)) %>%
      mutate(
        x = rnorm((reps + 1) * nrow(data), mean = mean(orig.data), sd = sd(orig.data))
      ) 
    
    if (hide) { 
      orig <- base::sample(1:(reps + 1), 1)
    } else {
      PlotData$rep <- PlotData$rep - 1
      orig <- 0
    }
    
    PlotData$rep_label = paste("sim", PlotData$rep)
    PlotData[PlotData$rep == orig, "x"] <- orig.data
    
    if (!hide) {
      PlotData[PlotData$rep == orig, "rep_label"] <- "original data"
    }
    
    PlotData$rep_label <- reorder(PlotData$rep_label, PlotData$rep)
      
    ggformula::gf_qq(~ x, data = PlotData, ...) %>%
      gf_facet_wrap( ~ rep_label, scales = scales)
}

qqnormsim2(length, data = KidsFeet, reps = 11)
```

![](https://i.imgur.com/O3aLMlt.png)

``` r
qqnormsim2(length, data = KidsFeet, reps = 11, size = 0.4, color = "red", hide = TRUE)
```

![](https://i.imgur.com/blIs4Go.png)

Created on 2018-07-02 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by mine-cetinkaya-rundel** [comment]
Thanks for the ideas @rpruim! We've greatly reduced the use of this function in our labs, and in fact, have moved away from trying to teach normal probability plots. Therefore I will close this issue for now. Happy to accept PRs if that's something you'd like to see implemented in the package!
