### ISSUE TITLE
Remove message that appears when package loads

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [OpenIntroStat/openintro#3]
Referring to the text that says "Please visit openintro.org for free statistics". It shows up in the compiled markdown documents (as shown below), and yes, it's possible to mute that with the `message = FALSE` option in the chunk, but I think we want to be careful about teaching those to students who are new to R.

<img width="596" alt="screen shot 2015-09-16 at 17 05 26" src="https://cloud.githubusercontent.com/assets/5965649/9918525/57768894-5c95-11e5-8363-c80adce0e531.png">

Leaving the issue here to be consider before the next version of the package...

**Comment by andrewpbray** [comment]
I don't have a strong feeling one way the other here but I am sympathetic to clean .Rmd lab reports. Is it possible to have a messageless loading, i.e. if we remove that statement, will the notice about attaching still appear? If so, seems like we'll need `message = FALSE` in the .Rmd regardless.

**Comment by mine-cetinkaya-rundel** [comment]
That, I believe, will still appear. But that is an R related message that is pretty crucial. 

Of course another option is to clear the package of duplicated name objects. Currently it's just the cars dataset.

**Comment by rpruim** [comment]
Including a data set that masks a data set in `datasets` seems like a bad choice.  There must be another name you could use.

Name collisions are a pain (and to some extent unavoidable).  But here it seems clear which package has priority and which package should change to avoid the unnecessary conflict.
