### ISSUE TITLE
Add Nick Paterno to the package author list before next CRAN release

### ISSUE THREAD

**Issue by DavidDiez** [OpenIntroStat/openintro#30]
Nick has added a handful of data sets.

**Comment by mine-cetinkaya-rundel** [comment]
@npaterno let me know which email address to add for you and if you have an ORCID number you'd like to add as well. Feel free to make a PR for this or give me the info and I can add it on!

**Comment by npaterno** [comment]
@mine-cetinkaya-rundel 

No ORCID. For email let's use nicholas.paterno@gmail.com. Thanks!
