### ISSUE TITLE
add "babies" dataset referenced in EOCE 6.1 of ISRS

### ISSUE THREAD

**Issue by beanumber** [OpenIntroStat/openintro#4]
Unless I am missing it, this is neither the `births` nor the `ncbirths` data set. 

Side note: Is it necessary to have both `births` and `ncbirths`?

**Comment by beanumber** [comment]
Oh...nevermind. 
It seems that this is the same as `mosaicData::Gestation`
But then shouldn't this package import `mosaicData`?

**Comment by beanumber** [comment]
Upon further review, these data sets do not appear to be the same. In particular, the `parity` and `smoke` variables are handled differently. In `babies` they are binary, but in `mosaicData::Gestation` they are not. 

Can anyone illuminate?

**Comment by mine-cetinkaya-rundel** [comment]
I'm afraid there is a data provenance issue here and I have not been able to track down the origin any further than what is stated in the help file of the package.

**Comment by mine-cetinkaya-rundel** [comment]
More on this at https://twitter.com/AmeliaMN/status/1331037890382467076?s=20

@AmeliaMN @hardin47

**Comment by AmeliaMN** [comment]
I feel like this could be a good opportunity to update the ncbirths dataset, using data from 2019. Pretty sure all my wrangling code would work on the new data, the only tricky piece is that real ages are redacted in the public-facing data, so the only thing available are ranges. Maybe someone has a smart idea for how to impute some ages or just randomly assign an age in the range.

**Comment by mine-cetinkaya-rundel** [comment]
I think it's a great idea to have the updated datasets here @AmeliaMN! We use the existing dataset in current books so I'd hesitate to replace it -- we can put a note in the docs clarifying the provenance issue as well as suggesting using the newer version. Once it's out of all the most recent editions of the books we could consider deprecating it.

I wonder about naming, how about `ncbirths19`?

Also, ages, hm... First question that comes to mind is, do we have to have ages? I don't have a great suggestion for imputing but could look up an appropriate method. Selecting from a random distribution in the range should be straightforward.

**Comment by AmeliaMN** [comment]
That's fair, and I have seen other textbooks do similar things. For example, `Stat2Data::BaseballTimes` vs `Stat2Data::BaseballTimes2017` or `Lock5Data::HollywoodMovies` vs `Lock5Data::HollywoodMovies2011`. I think ages was a nice variable because it is numeric, and this dataset gets used places like the [inference for numeric data](https://www.amelia.mn/sds220/labs/inf_for_numerical_data.html) lab (that's probably an old link, just easy to put my hands on) and you [exploring NC births](http://www2.stat.duke.edu/~mc301/ARTSCI101_Su16/post/r/nc_births.html) lab.

**Comment by mine-cetinkaya-rundel** [comment]
Given that the age bands are not very wide, I wouldn't be opposed to a random draw from a uniform in that range. We can place the data prep code in the `data-raw` folder. I'd be happy to do this based on your work or a PR is good too, whichever you prefer!

**Comment by AmeliaMN** [comment]
I started working on a PR and realized a couple things: 1. it seems like the most recent natality data is from 2014, and 2. probably the reason the `ncbirths` data was from 2004 is that is the last year the data included state information! So, I could make a `births14` dataset that would have random babies born in 2014, but they wouldn't necessarily be from North Carolina.

**Comment by mine-cetinkaya-rundel** [comment]
I think that's perfectly fine!
