### ISSUE TITLE
code by chapter

### ISSUE THREAD

**Issue by ajkl** [OpenIntroStat/openintro#6]
Is there a place where I can find the R code by chapter for the openintro book ?

**Comment by mine-cetinkaya-rundel** [comment]
The code for reproducing the figures in the textbook can be found in the repo of the textbook at https://github.com/OpenIntroOrg/openintro-statistics. Each chapter has a figures folder, and each figure has its own folder containing the R code and the image of the figure.

**Comment by beanumber** [comment]
I'm sure this is not high on anyone's priority list, but would it be easier if the book was written as `.Rnw` files with the code for the figures embedded?

**Comment by mine-cetinkaya-rundel** [comment]
@beanumber I agree that this would be good, but it is indeed too much of an undertaking that would come at the expense of other development that I'm not sure it can be high priority. It's a good idea for future development of new books though.
