### ISSUE TITLE
[Bug]: fastfood data has incorrect salad variable

### ISSUE THREAD

**Issue by VectorPosse** [OpenIntroStat/openintro#64]
### Contact Details

sraleigh@westminstercollege.edu

### Bug

The `fastfood` data set has a `salad` variable with all 515 values "Other". Looking at the item descriptions, it does appear that there are actual salads in the data set.

### Reproducible Example

library(openintro)
#> Loading required package: airports
#> Loading required package: cherryblossom
#> Loading required package: usdata
table(fastfood$salad)
#> 
#> Other 
#>   515

### Expected Behavior

I expected to see some foods classified as salads and others, not.

**Comment by mine-cetinkaya-rundel** [comment]
Need to double check but I believe this is https://github.com/rfordatascience/tidytuesday/tree/master/data/2018/2018-09-04 which has the same issue. So it might not be able to be fixed, but we should cite the source.

**Comment by hardin47** [comment]
I added the source here: b6dc90f7836e264d6a564da6dfe200aee341584d  Feel free to close this issue.
