### ISSUE TITLE
Description sentence

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [OpenIntroStat/openintro#75]
Make dataset one word in DESCRIPTION

**Comment by hardin47** [comment]
And in the title of the package?  

Mine Çetinkaya-Rundel, David Diez, Andrew Bray, Albert Kim, Ben Baumer, Chester Ismay and Christopher Barr (2020).
   openintro: Data Sets and Supplemental Functions from 'OpenIntro' Textbooks and Labs.
  R package version 2.0.0.
  [https://github.com/OpenIntroStat/openintro](https://github.com/OpenIntroStat/openintro).
