### ISSUE TITLE
yrbss isn't in the OpenIntro packages

### ISSUE THREAD

**Issue by dragonshill** [OpenIntroStat/openintro#8]
Hi,
the yrbss data is used in the OpenIntro text.
The yrbss data is available to download on the Github site.
So far as I can tell, the yrbss data hasn't been added to the OpenIntro packages.
Should it be?

**Comment by mine-cetinkaya-rundel** [comment]
This dataset is now in the package, see https://github.com/OpenIntroOrg/openintro-r-package/blob/master/openintro/data/yrbss.rda.
