### ISSUE TITLE
Push new package version to CRAN?

### ISSUE THREAD

**Issue by ncarchedi** [OpenIntroStat/openintro#9]
@mine-cetinkaya-rundel can we push a new version of `openintro` to [CRAN](https://cran.r-project.org/web/packages/openintro/index.html)? We're using the latest version from github in your datacamp courses, but I think there's been some confusion among students since it differs from what's on CRAN.

**Comment by beanumber** [comment]
Yes, please! The GitHub version is 1.6.1 but the CRAN version is still 1.4!

**Comment by mine-cetinkaya-rundel** [comment]
New version is up on CRAN: https://cran.r-project.org/web/packages/openintro/index.html
